version: '3.8'
services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
